hastexo/tutor-contrib-s3

- setup.py
- tutors3/__about__.py
Rather than hard-coding the version number in `__about__.py`, derive the version number from a Git tag with `setuptools-scm` (and then set the version number in `__about__.py` from that).
> Use setuptools-scm, and derive the version number from Git tags

- .bumpversion.cfg
- CHANGELOG.md
- HACKING.md
- tox.ini
Add a few bits and pieces that make release management easier:
* Add configuration for `bump2version` (the maintained fork/workalike of bumpversion).
* Add a tox testenv, `bumpversion`, so that a release manager can easily cut a new release with `tox -e bumpversion`.
* Add `HACKING.md` explaining the process.
* Add `CHANGELOG.md` for tracking changes.
Reference: <https://pypi.org/project/bump2version/>
> Add release management scaffolding

- CHANGELOG.md
- README.md
README.md:
* Explain the difference between tutor-contrib-s3 and tutor-minio.
* Document the recently changed default for S3_HOST.
CHANGELOG.md:
* Mention the recent renaming from tutor-s3 to tutor-contrib-s3.
> Minor fixes to README and CHANGELOG

- .bumpversion.cfg
- .githooks/post-commit
- .gitlab-ci.yml
- .gitlint
- HACKING.md
- tox.ini
Both Tutor and Open edX enforce the [Conventional Commits](https://www.conventionalcommits.org/) message format as outlined in [OEP-0051](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html). Enforce that standard here as well:
* Implement commit message testing with Gitlint.
* Use the Gitlint `contrib-title-conventional-commits` rule configuration option to enforce the commit message prefixes that
OEP-0051 defines.
* Add gitlint integration to tox.
* Add a post-commit hook that validates the most recent commit message with Gitlint. That way, a commit with a non-compliant commit message will succeed, but the user sees a warning from the failed gitlint run (and then has the chance to amend the commit). The reason we do it this way and …
> build: Use Gitlint to enforce commit message style

- .bumpversion.cfg
- .githooks/post-commit
- .gitlab-ci.yml
- .gitlint
- HACKING.md
- README.md
- tox.ini
This is a follow-on PR to #14, and fixes a couple of issues with the README:
* `S3_USE_SSL` is a boolean; remove the quotes around the literal (otherwise, setting `S3_USE_SSL` to `"False"` in quotes will lead to the boolean being evaluated as `true`)
* `S3_ADDRESSING_STYLE` and `S3_SIGNATURE_VERSION` are strings, add quotes around the literals.
*  We mention `S3_PROFILE_IMAGE_CUSTOM_DOMAIN` and `S3_PROFILE_IMAGE_MAX_AGE` in the README, but the plugin presently does not do anything with those values. Remove them from the README as long as we don't support them.
> Minor updates to the README

- LICENSE.md
We already specified AGPL v3 in the setup.py `classifiers` list, but it doesn't hurt to include the license text itself in the repository.
> docs: Add LICENSE.md

- .bumpversion.cfg
- README.md
As long as we don't have a release up on PyPI, instruct people to
install from Git, pointing them to the most recent release.
Update .bumpversion.cfg so that we update the README with the latest
version on every release.
Also, fix a double colon ("::") in the README that was left over from
the ReST→Markdown conversion.
> docs: Update README to mention pip install from GitHub

- README.md
Add a note indicating that some values may be optional or required to
set depending on circumstances, based on which S3 implementation is
being used.
> docs: Update README section on configuration values

- README.md
- tutors3/patches/openedx-common-settings
- tutors3/plugin.py
Setting a value for `AWS_S3_ENDPOINT_URL` overrides
`AWS_S3_ADDRESSING_STYLE` settings.
Not setting it allows `django-storages` to build the correct AWS path
incorporating `AWS_S3_ADDRESSING_STYLE` and
`AWS_S3_ADDRESSING_REGION`.
So we should only set `AWS_S3_ENDPOINT_URL` if we explicitly want to
use a different S3 host than AWS.
Fixes issue #22.
> fix: Only set AWS_S3_ENDPOINT_URL if not using AWS

- tutors3/patches/openedx-common-settings
We previously used `ENABLE_HTTPS` when constructing `AWS_S3_ENDPOINT_URL` to determine whether we wanted to connect to `S3_HOST` via HTTP or HTTPS. `Use S3_USE_SSL` instead, as we do for the other SSL-related settings.
> fix: Honour S3_USE_SSL when setting AWS_S3_ENDPOINT_URL

- .github/ISSUE_TEMPLATE/bug_report.md
When rendered in GitHub for opening an issue, the 80-column line wrap looks bad in the preview. Since everything about the bug report template is for making it easy to submit good bug reports, and UI impressions matter for perceived ease of use, remove the extraneous newlines and let the GitHub issue UI reflow the text as needed.
> docs: Remove wrapped paragraphs in bug report template

- README.md
Make it clear that `S3_CUSTOM_DOMAIN` configuration parameter should not
be set when using AWS S3.
> docs: S3_CUSTOM_DOMAIN should not be set with AWS

- tutors3/patches/openedx-lms-common-settings
When in development (`DEBUG==True`), a non-empty `base_url` is necessary
to build static URLs for profile images.
Resolves #41
> fix: Add base_url to profile image backend

- README-aws.md
- README.md
An example that will suit most use cases of setting up a S3 Bucket.
Resolves #37
> docs: add documentation explaining how to configure a S3 Bucket

- README.md
- tutors3/patches/openedx-lms-common-settings
- tutors3/plugin.py
Without this patch when the plugin is activated all file are saved in an
S3 Bucket or an API-compatible storage. We don't have the option to keep
the profile pictures in the filesystem.
This is a problem because Open edX makes it possible to configure
individually each type of data, such as Grades, Reports, Profiles
Pictures, ORA2 files, etc.
This patch solves the problem by add the ability to continue using the
filesystem for profile pictures when the plugin is activated.
Use:
- When `S3_PROFILE_IMAGE_BUCKET` is empty the profile pictures will be
saved in filesystem. The default `PROFILE_IMAGE_BACKEND` won't be
overwritten.
- When `S3_PROFILE_IMAGE_BUCKET` is set the profile pictures will
be saved in an S3 Bucket that must have a public ACL. The
`PROFILE_IMAGE_BACKEND` will be …
> feat: add ability to disable profile pictures to use S3 bucket

- CHANGELOG.md
- setup.py
- tutors3/plugin.py
Use Tutor v1 plugin API instead of the legacy v0 API.
Reference: https://github.com/overhangio/cookiecutter-tutor-plugin#migrating-from-v0-plugins
> refactor: Use Tutor v1 plugin API

- .bumpversion.cfg
- CHANGELOG.md
- README.md
As of this release, the plugin supports Tutor 14 and hence Open edX Nutmeg.
> Prepare release

- .github/workflows/tox.yml
- .gitlab-ci.yml
- CHANGELOG.md
- README.md
- setup.py
- tox.ini
This plugin works perfectly with the latest release of tutor as-is, so this change expands its compatibility to work with the latest relese.
> chore: bump supported tutor versions to work on tutor 16 for palm

- README.md
We started supporting Nutmeg with 1.0.0, Olive with 1.1.0, and Palm with 1.2.0. Technically all three Open edX releases *should* work in conjunction with whatever is the latest state of `main`, but it probably doesn't hurt to recommend that people use a minor version to match the Open edX release which we regularly test at the time we tag the minor.
Thus, update the version compatibility matrix in the README accordingly.
> docs: Update version compatibility matrix in README

- CHANGELOG.md
- README.md
- setup.py
This PR bumps Tutor to v17 to support Quince. Also, it updates the changelog and the compatibility matrix.
> Bump tutor requirements to allow v17

- .github/workflows/tox.yml
- CHANGELOG.md
- tox.ini
- tutors3/__about__.py
- tutors3/plugin.py
* Replace the use of pkg_resources (from setuptools, which is no longer included in virtual environments as of 3.12) with importlib.metadata and importlib_resources.
* Add Python 3.12 to the test matrix.
> feat: Support Python 3.12

- CHANGELOG.md
- README.md
- setup.py
Add support for tutor 18 (Redwood)
Private Ref : OpenCraft Internal ticket [BB-8942](https://tasks.opencraft.com/browse/BB-8942)
> chore: bump supported tutor versions to work on tutor 18 for redwood

- CHANGELOG.md
- README.md
- tutors3/patches/openedx-common-settings
- tutors3/plugin.py
Introduce a new configuration option, `S3_DEFAULT_ACL`, defaulting to `None`.
When set, this populates the `AWS_DEFAULT_ACL` option for the S3Storage backend.
Reference:
https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#settings
> feat: Introduce S3_DEFAULT_ACL

- .github/workflows/tox.yml
These are substantially the same changes as in https://github.com/hastexo/tutor-contrib-backup/pull/87 (minus the README updates).
> Bump GitHub Actions 

- CHANGELOG.md
- README.md
- setup.py
Add support for tutor 19 (Sumac)
Private Ref : OpenCraft Internal ticket [BB-9353](https://tasks.opencraft.com/browse/BB-9353)
> chore: bump supported tutor versions to work on tutor 19 for sumac

- CHANGELOG.md
- tutors3/patches/openedx-common-settings
Add the missing import statement for `botocore.client import Config` when setting the AWS_S3_CLIENT_CONFIG variable.
> fix: Add missing import statement
